//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace filmo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_filmo
    {
        public int pkID { get; set; }
        public string Titr { get; set; }
        public string TextValue { get; set; }
    }
}
